In [1]:
import os

def find_missing_files(directory):
    jpg_files = set()
    xml_files = set()

    # Walk through the directory and collect .jpg and .xml file names without extensions
    for file_name in os.listdir(directory):
        if file_name.endswith('.jpg'):
            jpg_files.add(file_name[:-4])
        elif file_name.endswith('.xml'):
            xml_files.add(file_name[:-4])
    
    # Find missing .xml files for each .jpg file
    missing_xml_files = jpg_files - xml_files
    # Find missing .jpg files for each .xml file
    missing_jpg_files = xml_files - jpg_files

    # Print missing files
    if missing_xml_files:
        print("Missing .xml files for the following .jpg files:")
        for file_name in missing_xml_files:
            print(f"{file_name}.jpg")
    
    if missing_jpg_files:
        print("Missing .jpg files for the following .xml files:")
        for file_name in missing_jpg_files:
            print(f"{file_name}.xml")

# Replace 'your_directory_path' with the path to your directory
find_missing_files('Val')

Missing .xml files for the following .jpg files:
4542.jpg
2839.jpg
0992.jpg


In [2]:
import numpy as np

# test = np.load('../test/img_0001_test.npy')
test = np.load('../test/img_0720_train.npy')
print(test)

[[ 151.4106   1876.5825    276.90872 ]
 [ 183.36658  1620.9347    139.4184  ]
 [  55.54264  1551.6967     61.68395 ]
 [ 577.49036  1615.6086     90.72159 ]
 [ 715.9663   1658.2167    128.62547 ]
 [ 300.97867  1696.1644    137.26845 ]
 [ 217.09422  1452.5        59.598938]
 [  58.645805 1493.7765     29.508265]
 [ 298.31567  1500.434      48.78014 ]
 [ 355.57016  1487.119      77.05401 ]
 [ 462.0901   1527.064     104.06982 ]
 [  16.25791  1440.1354     76.97291 ]
 [  72.84663  1466.7654     43.96152 ]
 [ 111.46011  1470.7599     31.732178]
 [ 149.40784  1492.0638     54.580364]
 [ 159.39409  1451.4531     50.40361 ]
 [ 257.25928  1483.409      44.638287]
 [ 287.21802  1458.7764     37.838764]
 [ 477.51218  1440.133      49.66905 ]
 [ 610.6621   1492.7273     64.04809 ]
 [ 598.67865  1453.4481     46.335358]
 [ 580.03766  1414.8346     52.951015]
 [ 517.45715  1420.8264     46.823223]
 [ 651.9386   1439.4674     44.878956]
 [ 665.9193   1424.1552     52.398144]
 [ 693.8808   1480.7439  

In [18]:
# NOTE: tested with python 3.8
from scipy.io import loadmat

points = loadmat('../test/img_1058_ann.mat')['annPoints'].astype(np.float32)
# points = loadmat('../test/GT_IMG_184.mat')['image_info'][0][0][0][0]
print(points)


[[2541.6968   719.3083 ]
 [1677.4482   169.04922]
 [1686.7747   200.1373 ]
 ...
 [1692.5768   259.85947]
 [1551.1628   922.9751 ]
 [1583.3057   940.50757]]
